### ISSUE TITLE
Figma App Design - sorting and price display feature. Also the ability to sort the prices from low to high

### ISSUE THREAD

**Issue by tommyshelby3** [cse442-at-ub/project_s23-gofly#10]
*** For sorting ***

Test 1: Checking 1 available airline flight with a single price.

Get on to the GoFly (do not need to log in or signup)
Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
The search result returns the flight options in an unorderly price list.
Click the sort by price option in the top right corner.
No matter if you choose low-high or high-low sort by price option, it will return only that single price.
Test 2: Checking 1 or more available airline flights with a single price.

Get on to the GoFly (do not need to log in or signup)
Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
The search result returns the flight options in an unorderly price list.
Click the sort by price option in the top right corner.
No matter if you choose low-high or high-low sort by price option, it will return only that specific price that is the same for every option.
Test 3: Checking 1 or more available airline flights with different prices.

Get on to the GoFly (do not need to log in or signup)
Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
The search result returns the flight options in an unorderly price list.
Click the sort by price option in the top right corner.
Choose the low-high price option.
The new search result will consist of flight options in ascending order in terms of price.
Test 4: Checking 1 or more available airline flights with different prices.

Get on to the GoFly (do not need to log in or signup)
Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
The search result returns the flight options in an unorderly price list.
Click the sort by price option in the top right corner.
Choose the high-low price option.
The new search result will consist of flight options in descending order in terms of price.
Test 5: Checking 1 or more available airline flights with different prices.

Get on to the GoFly (do not need to log in or signup)
Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
The search result returns the first flight option as the lowest.
Click the sort by price option in the top right corner.
Choose the low-high price option.
The new search result will still have that specific lowest price at the top and follow the low to high sorted order for the next available options.

*** For Price Display ***

Test 1: Checking Price Display

Search for a flight from BUF to LGA on 08/12/2023
Verify the airplane route is for that specific flight
Verify that all options of flights indicate their specific prices

**Comment by mdhyder01** [comment]
**Test Task**

Test 1: Checking Price Display
1. Search for a flight from BUF to LGA on 08/12/2023
2. Verify the airplane route is for that specific flight
3. Verify that all options of flights indicate their specific prices

**Comment by tommyshelby3** [comment]
*** For sorting ***

Test 1: Checking 1 available airline flight with a single price.

1. Get on to the GoFly (do not need to log in or signup)
2. Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
3. The search result returns the flight options in an unorderly price list.
4. Click the sort by price option in the top right corner. 
5. No matter if you choose low-high or high-low sort by price option, it will return only that single price.


Test 2: Checking 1 or more available airline flights with a single price.

1. Get on to the GoFly (do not need to log in or signup)
2. Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
3. The search result returns the flight options in an unorderly price list.
4. Click the sort by price option in the top right corner. 
5. No matter if you choose low-high or high-low sort by price option, it will return only that specific price that is the same for every option.

Test 3: Checking 1 or more available airline flights with different prices.

1. Get on to the GoFly (do not need to log in or signup)
2. Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
3. The search result returns the flight options in an unorderly price list.
4. Click the sort by price option in the top right corner. 
5. Choose the low-high price option.
6. The new search result will consist of flight options in ascending order in terms of price.

Test 4: Checking 1 or more available airline flights with different prices.

1. Get on to the GoFly (do not need to log in or signup)
2. Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
3. The search result returns the flight options in an unorderly price list.
4. Click the sort by price option in the top right corner. 
5. Choose the high-low price option.
6. The new search result will consist of flight options in descending order in terms of price.

Test 5: Checking 1 or more available airline flights with different prices.

1. Get on to the GoFly (do not need to log in or signup)
2. Search for a specific flight using the date, departure-destination airport, # of tickets, and flight class.
3. The search result returns the first flight option as the lowest.
4. Click the sort by price option in the top right corner. 
5. Choose the low-high price option.
6. The new search result will still have that specific lowest price at the top and follow the low to high sorted order for the next available options.
