### ISSUE TITLE
Bug Fixes/ CSS And Design Update

### ISSUE THREAD

**Issue by tommyshelby3** [cse442-at-ub/project_s23-gofly#19]
*** Task Tests ***

username: no
password: no 

Test 1: Bug Fixes for Reviews Feature

1. Navigate to the login page and log in using the above credentials.
2. Click on the "Reviews" option in the navigation bar and confirm that you are redirected to the GoFly review page.
3. Submit a review with a positive experience and a 5-star rating, then click the "View Reviews" button and verify that the posted review appears on the "Our Customer Reviews" page.
4. Submit a review with a negative experience and a 1-star rating, then click the "View Reviews" button and verify that the posted review appears on the "Our Customer Reviews" page.

Test 2: CSS and Design Update for Reviews Feature

1. Verify that the reviews feature is consistent with the overall design and branding of the website.
2. Implement the design update using CSS and verify that the reviews feature looks and functions as intended.
3. Verify that the reviews feature is accessible to users with disabilities by using an appropriate color contrast.

Test 3: Bug Fixes for Edit Review Feature

1. Log into the account using the "no" credentials and navigate to the "Reviews" page.
2. Click on the 3-dotted bar next to a review submitted by the test user and verify that a dropdown box pops up with the "Edit" option.
3. Click on the "Edit" option and confirm that you are redirected to the "Edit Your Review" page.
4. Edit the content in the comment box, select a different star rating, and click the "Update" button to update the review.
5. Verify that the updated review appears on the "Our Customer Reviews" page with the new comment and selected rating.

Test 4: Weather Forecast Accuracy and Presentation

1. Click on the "Listings" option in the top navigation bar and confirm that you are redirected to the display listing page.
2. Verify that there is a "Weather" button on every ticket section, and click it to navigate to the GoFly weather forecast page.
3. Enter a valid destination in the search bar (e.g., "New York") and click the search button.
4. Verify that the displayed weather forecast for the entered destination is accurate and up-to-date, comparing it with a reliable weather source (e.g., a weather website or app).
5. Confirm that the weather forecast information is presented in a visually appealing and easy-to-read format.

Test 5: Error Handling for Invalid Destinations

1. Enter an invalid destination in the search bar (e.g., "243532564") and click the search button.
2. Verify that an empty box is being displayed.

Test 6: Weather Forecast Updates for Different Destinations

1. Enter a new valid destination in the search bar (e.g., "San Francisco") and click the search button.
2. Verify that the weather forecast for the entered destination is updated and displayed, including accurate and up-to-date information.
3. Repeat the process for multiple destinations to ensure that the weather forecast feature functions consistently.

Test 7: Responsive Design and Cross-Browser Compatibility

1. Verify that the weather forecast page is responsive, with the layout adjusting accordingly when viewed on different screen sizes (desktop and mobile).
2. Check the accessibility of the weather forecast feature, ensuring that it is usable for people with disabilities, such as providing appropriate color contrast.

**Comment by abdullahsyedz** [comment]
rewrite acceptance tests for this as per style guide
