### ISSUE TITLE
Bug Fixes/ CSS And Design Update (Admin)

### ISSUE THREAD

**Issue by fardinchowdhury** [cse442-at-ub/project_s23-gofly#2]
**Tasks Tests**

Test 1: Navbar bug fixes
   - Log in to GoFly account ([Link](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442y/login.php))
         - username: admin
         - password: admin
   - Verify that it goes to the admin landing page. Check if the address bar towards the end of "admin_landing.php"
   - Verify that the navigation bar contains "Post Flights" and "Post Hotels"

Test 2: Redirecting Post Flight Bugs Fix
   - Log in to GoFly account ([Link](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442y/login.php))
         - username: admin
         - password: admin
   - Verify that it goes to the admin landing page. Check if the address bar towards the end of "admin_landing.php"
   - Verify that the navigation bar contains "Post Flights" and "Post Hotels"
   - Click on "Post Flights"
          - Verify that the page redirects to a form where the admin can create flight listings. 
  
Test 3: Redirecting Post Hotels Bugs Fix
   - Log in to GoFly account ([Link](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442y/login.php))
         - username: admin
         - password: admin
   - Verify that it goes to the admin landing page. Check if the address bar towards the end of "admin_landing.php"
   - Verify that the navigation bar contains "Post Flights" and "Post Hotels"
   - Click on "Post Hotels"
          - Verify that the page redirects to a form where the admin can create hotel listings.

**Comment by abdullahsyedz** [comment]
rewrite acceptance tests for this
