### ISSUE TITLE
CSS/bug fix and design (booking)

### ISSUE THREAD

**Issue by fardinchowdhury** [cse442-at-ub/project_s23-gofly#5]
Tasks Tests

Test 1: Display Correct Listings

Link for Login Page: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442y/login.php

1. Log in to GoFly account 
- username: rom
- password: 12345

2. Verify that there is a Listing Dropdown on the nav bar that has flights and hotels.
3. Verify no error is given and redirection is correct. Flights lead to flight ticket lists and hotels lead to hotel listings.

Test 2: Display Correct Bookings

1. Log in to GoFly account (Link)
- username: rom
- password: 12345

2. On the nav bar, verify that there is a My Booking option and it redirects to the user's my booking page.
3. On my booking page, verify there is a tab for flights and hotels. Verify that the flight tab displays all booked tickets and the hotel tab displays all booked hotels.
4. If there is nothing displayed for either flights or hotels or both, that means the user has no bookings.

Test 3: Bug Fix with Canceling Flight and Hotel Bookings
1. Log in to GoFly account (Link)
- username: rom
- password: 12345
2. On the nav bar, go to my booking.
3. There should already be some listed bookings for this user. Verify it's there.
4. Click on the flight's tabs, and for the flight tickets click the delete ticket button to the right of the ticket.
5. Verify that the ticket is no longer in my booking.
6. Go to the hotel's tab. Click the cancel booking button and navigate back to the hotel tab.
7. Verify that the hotel booking is no longer there.

**Comment by abdullahsyedz** [comment]
rewrite acceptance tests for this
