### ISSUE TITLE
Figma App Design - Customer support Feature 

### ISSUE THREAD

**Issue by abdullahsyedz** [cse442-at-ub/project_s23-gofly#6]
**Task Test**

Test 1: Submitting a valid contact form

1. Go to the Contact page.
2. Fill in the required fields where the username doesn't match anyone else in database, valid email and messages.
3. Click the "Submit" button.
4. Verify that a success message appears on the screen.
5.  Verify that the message was delivered to the appropriate recipient.

Test 2: Submitting an incomplete contact form

1. Go to the Contact page.
2. Fill in some but not all required fields.
3. Click the "Submit" button.
4. Verify that an error message appears indicating which fields are missing.
5. Verify that the form is not submitted until all required fields are filled.

Test 3: Submitting a contact form with invalid input

1. Go to the Contact page.
2. Enter invalid input in one or more fields (example: an invalid email address).
3. Click the "Submit" button.
4. Verify that an error message appears indicating which fields contain invalid input.
5. Verify that the form is not submitted until all input is valid.

Test 4: Contact form without captcha

1. Go to the Contact page.
2. Fill in the required fields 
3. Submit the form without completing the captcha.
4. Verify that an error message appears indicating that the captcha must be completed.
5. Verify that the form is not submitted until the captcha is completed.

Test 5: Contact form with captcha

1. Go to the Contact page.
2. Fill in the required fields 
3. Complete the captcha.
4. Click the "Submit" button.
5. Verify that a success message appears on the screen.
6. Verify that the message was delivered to the appropriate recipient.

**Comment by fardinchowdhury** [comment]
https://www.figma.com/file/rJ2G7ee4duuk7vXHZ9FnBD/Wireframing?node-id=3%3A78&t=hpFzziWYdGEy6avb-1
