### ISSUE TITLE
As a GoFly customer, I want to be able to edit my review on my experience so that I can update my feedback and provide accurate information to other customers. 

### ISSUE THREAD

**Issue by tommyshelby3** [cse442-at-ub/project_s23-gofly#63]
*** Acceptance Tests ***

Username: no
Password: no

Test 1 - Access the edit review page

1. Log into the account using the above credentials. (Link)
2. Confirm that there is a "Reviews" option on the top navigation bar.
3. Click the "Reviews" option to redirect you to the GoFly review page.
4. Click on the 3-dotted bar next to a review submitted by the test user and verify that a dropdown box pops up with the "Edit" option.
5. Click on the "Edit" option and confirm that you are redirected to the "Edit Your Review" page.

Test 2 - Edit review form availability

1. On the edit review page, verify that the review form is available with the following fields: full name, comment box, and 1 to 5-star rating selection.
2. Also, confirm that there is an "Update" button.
3. Verify that there is a "View Customer Reviews" button under the "Update" button.

Test 3 - Edit and update a review

1. Change the content in the comment box to a new experience (e.g., "East and fast booking process!").
2. Select a different star rating to indicate a change in the experience.
3. Click the "Update" button to update the review.
4. Verify that the review is successfully updated.
5. Once the "View Customer Reviews" button is clicked, confirm that the page is redirected to the "Our Customer Reviews" page.
6. Confirm that the updated review appears on the review page with the new comment and selected rating.

**Comment by abdullahsyedz** [comment]
rewrite these acceptance tests as per style guide
