### ISSUE TITLE
Return Flights -Frontend/Backend

### ISSUE THREAD

**Issue by fardinchowdhury** [cse442-at-ub/project_s23-gofly#65]
**Task Test**
Test 1: Verify if the return flights are displayed

- Log in to the system using valid credentials
- Username : rom. Password: 12345
- Search for  flight
- Select the option for a return flight.
- Select departure date June 6th 2023 and Arrival August 8th 2023
- Verify that the departure flights are displayed on the display page.
- Make sure to Select a departure flight.
- Ensure that the arrival flights are displayed with the correct dates, times, and prices.

Test 2: Verify if the user can select a return flight

- Log in to the system using valid credentials
- Username : rom. Password: 12345
- Search for  flight
- Select the option for a return flight.
- checkout for return flight. 
- Verify that the return flights are displayed on the booking results page.
- Ensure that the selected return flight details are correct.

Test 3: Verify if the return flights are filtered by departure time

- Connect to the database using valid credentials.
- Retrieve the flight data for a round-trip flight.
- Filter the return flights to show only flights departing in the afternoon.
- Verify that the return flights are displayed with the correct departure times.
- Ensure that the flight data includes the correct dates, times, and prices.

Test 4: Verify if the return flights are retrieved from the database

- Connect to the database using valid credentials.
- Retrieve the flight data for a round-trip flight.
- Verify that the return flight data is retrieved from the database.
- Ensure that the flight data includes the correct dates, times, and prices.

**Comment by abdullahsyedz** [comment]
write task tests for this
