### ISSUE TITLE
As a traveler, I want to b able to see the weather forecast for my destination so that I can plan and prepare accordingly for the weather conditions during my trip.

### ISSUE THREAD

**Issue by tommyshelby3** [cse442-at-ub/project_s23-gofly#67]
*** Acceptance Tests ***

Username: no
Password: no

*** Test 1 ***

1. Log into the account using the above credentials.
2. Verify that there is a "Listings" option at the top navigation bar and click on it.
3. Confirm that you are redirected to the display listing page and see the available plane tickets.
4. Verify that there is a "Weather" button on every ticket section.
5. Click the "Weather" option and confirm that you are redirected to the GoFly weather forecast page.
6. Verify that there is a search bar on the weather forecast page with the placeholder text "Enter your destination".
7. Enter a valid destination in the search bar (e.g., "New York") and click the search button.
8. Verify that the weather forecast for the entered destination is displayed, including the following information:

- Current temperature
- Weather condition (e.g., "Sunny", "Cloudy", "Rainy")
- High and low temperatures for the day
- A brief description of the weather (e.g., "Sunny with a chance of rain in the evening")

*** Test 2 ***

1. Enter an invalid destination in the search bar (e.g., "InvalidLocation") and click the search button.
2. Verify that an empty form is being displayed.

*** Test 3 ***

1. Enter a valid destination in the search bar (e.g., "San Francisco") and click the search button.
2. Verify that the weather forecast for the entered destination is updated and displayed, including the following information:

- Current temperature
- Weather condition (e.g., "Sunny", "Cloudy", "Rainy")
- High and low temperatures for the day
- A brief description of the weather (e.g., "Sunny with a chance of rain in the evening")

**Comment by abdullahsyedz** [comment]
Write task tests for this!
