### ISSUE TITLE
Weather Functionality 

### ISSUE THREAD

**Issue by tommyshelby3** [cse442-at-ub/project_s23-gofly#68]
*** Task Tests ***

Username: no
Password: no

1. Log into the account using the above credentials.
2. Verify that there is a "Listings" option at the top navigation bar and click on it.
3. Confirm that you are redirected to the display listing page and see the available plane tickets.
4. Verify that there is a "Weather" button on every ticket section.
5. Click the "Weather" option and confirm that you are redirected to the GoFly weather forecast page.
6. Verify that there is a search bar on the weather forecast page with the placeholder text "Enter your destination".
7. Enter a valid destination in the search bar (e.g., "New York") and click the search button.
8. Verify that the weather forecast for the entered destination is displayed, including the following information:

- Current temperature
- Weather condition (e.g., "Sunny", "Cloudy", "Rainy")
- High and low temperatures for the day
- A brief description of the weather (e.g., "Sunny with a chance of rain in the evening")

9. Enter an invalid destination in the search bar (e.g., "InvalidLocation") and click the search button.
10. Verify that an empty form is being displayed.

11. Enter a valid destination in the search bar (e.g., "Buffalo") and click the search button.
12. Verify that the weather forecast for the entered destination is updated and displayed, including the following information:

- Current temperature
- Weather condition (e.g., "Sunny", "Cloudy", "Rainy")
- High and low temperatures for the day
- A brief description of the weather (e.g., "Sunny with a chance of rain in the evening")

13. Verify that the weather forecast page is responsive and the layout is adjusted accordingly when viewed on different screen sizes (e.g., desktop, tablet, mobile).
14. Test the page on different browsers (e.g., Chrome, Firefox, Safari) and confirm that the weather forecast information is displayed correctly on each browser.

**Comment by abdullahsyedz** [comment]
Write task tests for this!
